# Generated by Django 5.1.1 on 2024-09-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(default='default@example.com', help_text='Enter a valid email address.', max_length=254)),
            ],
        ),
    ]
